### ISSUE TITLE
`DynGd` can't be nullable in exported `Array`

### ISSUE THREAD

**Issue by Gaspard--** [godot-rust/gdext#1147]
Hello !

I noticed that `Array<Option<DynGd<...>>>` doesn't work, which seems like a missed edge case.

The following are accepted (`T` and `U` are placeholders for real types):

```rust
#[export]
x: Array<Gd<T>>,

#[export]
y: Array<Option<Gd<T>>>,

#[export]
z: Array<DynGd<T, U>>,
```
`x` is a little cubbersome because godot allows array elements to be unset, which is why `y` is useful in those scenarios.
`z` will fail with a message when an unset element is present, however we can't do the following:

```rust
#[export]
w: Array<Option<DynGd<T, U>>>,
```
> error[E0277]: `Array<T>` can only store element types supported in Godot arrays (no nesting).

Obviously this is really minor, but looks like an oversight.

**Comment by Bromeon** [comment]
Definitely oversight, thanks for reporting! Since it's a feature not yet implemented rather than an existing feature working incorrectly, I relabeled it. Maybe even QoL rather than full-fledged feature 😛 

We can probably work on this for 0.3.1, for 0.3.0 we're currently only integrating critical fixes that can't be done in a backwards-compatible way, to not delay the release too much.

**Comment by Yarwin** [comment]
Related: https://github.com/godot-rust/gdext/issues/580#issuecomment-1929982127. 

Most `DynGd<T, D>`'s Godot traits are being delegated to `Gd<T>` – it would be nice to refactor `ArrayElement` in a fashion that would allow to store&export any godot-convertable element in the array, fixing this issue as well. (this also would allow us to remove Sealed for `DynGd` which is a bit silly, since `DynGd` is not GodotType 😄 ). 

(of course we can also slap some band-aid and just implement Sealed&ArrayElement for `Option<DynGd<T, D>>` but  eeeh)

**Comment by Bromeon** [comment]
> it would be nice to refactor `ArrayElement` in a fashion that would allow to store&export any godot-convertable element in the array

I don't see how that's possible, there are subtle differences between what's allowed in arrays ([`ArrayElement`](https://godot-rust.github.io/docs/gdext/master/godot/meta/trait.ArrayElement.html#foreign-impls)) and what can be converted to/from Godot ([`ToGodot`](https://godot-rust.github.io/docs/gdext/master/godot/prelude/trait.ToGodot.html#foreign-impls)). The former is deliberately stricter, it doesn't allow native-struct pointers, the unit type `()`, etc.

**Comment by Bromeon** [comment]
Implemented in https://github.com/godot-rust/gdext/pull/1323.
