### ISSUE TITLE
NavigationAgent2D is never built

### ISSUE THREAD

**Issue by scuzzycheese** [godot-rust/gdext#867]
Cannot seem find NavigationAgent2D no matter how hard I try. 

Cargo.toml:
```
[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["api-4-2"] }
```

Code:
```
use godot::prelude::*;
use godot::classes::{ICharacterBody2D};
use godot::classes::{CharacterBody2D}; // <- Don't know what to add to get NavigationAgent2D, have tried many imports. 
//use godot::classes::{CharacterBody2D, NavigationAgent2D}; <- Does not work either

#[derive(GodotClass)]
#[class(base=CharacterBody2D)]
pub struct Player {
    speed: real,
    screen_size: Vector2,

    #[base]
    base: Base<CharacterBody2D>,

    // #[export]
    go_to: Vector2,

    nav_agent: Option<Gd<NavigationAgent2D>>
}
```

Error without import:
```
error[E0412]: cannot find type `NavigationAgent2D` in this scope
  --> src/player.rs:17:26
   |
17 |     nav_agent: Option<Gd<NavigationAgent2D>>
   |                          ^^^^^^^^^^^^^^^^^ not found in this scope
   |
```

Error with import:
```
 --> src/player.rs:3:39
  |
3 | use godot::classes::{CharacterBody2D, NavigationAgent2D};
  |                                       ^^^^^^^^^^^^^^^^^ no `NavigationAgent2D` in `classes`
```

Searching for generated code:
```
$  find . | grep "character_body_"
./debug/build/godot-core-4eb11028a60413d2/out/classes/character_body_2d.rs
./debug/build/godot-core-4eb11028a60413d2/out/classes/character_body_3d.rs


$  find . | grep "navigation" <- No navigation Agent found anywhere in target directory
./debug/build/godot-core-4eb11028a60413d2/out/classes/navigation_mesh_source_geometry_data_2d.rs
./debug/build/godot-core-4eb11028a60413d2/out/classes/navigation_mesh_generator.rs
```

Not sure what's going on, but it seems the NavigationAgent2d (and 3d) are neger generated. This worked in the 4.1 version of the bindings, but no longer works in 4.2.

**Comment by Bromeon** [comment]
1. Go to [API docs ](https://godot-rust.github.io/docs/gdext/master/godot/) (linked in ReadMe -- add bookmark)
2. Type `NavigationAgent2D`
3. Open docs for that class
4. Read this: 
    ![image](https://github.com/user-attachments/assets/e835d962-6136-45b5-8717-25537cf37115)
5. Profit
