### ISSUE TITLE
Set proper api version when using `api-custom-json`.

### ISSUE THREAD

**Issue by Yarwin** [godot-rust/gdext#1570]
Currently when `api-custom-json` godot version – which defines `before_api` and `since_api` attributes - is being fetched from provided JSON, while the latest stable header is being used. This makes said feature unusable in case of a mismatch – when JSON specifies not yet stable version we might need functions from the gdextension header which are not present in the latest stable yet. (for example JSON sets version 4.7 -> we use it with 4.6 header -> 4.7 requires something from 4.7 header -> compilation error!)

Note that doing the reverse and treating header as source of truth doesn't help since the opposite is possible (due to RequiredPtr - removing unwraps) + being forced to always use the latest stable version is just silly (headers are backward compatible, 4.6 header will work fine with anything from 4.2).

Ideally just require that JSON version <= header version.

**Comment by Bromeon** [comment]
Note that "JSON" is now ambiguous, let's talk about "API"/"classes" (`extension_api.json`) vs. "header"/"interface" (`gdextension_interface.json`). The irony of the "I" in API is not lost on me, but I didn't name these...

---

> This makes said feature unusable in case of a mismatch – when JSON specifies not yet stable version we might need functions from the gdextension header which are not present in the latest stable yet.

Is this a common scenario though? Class APIs tend to evolve more quickly than the header itself...

Technically we can update the `gdextension-api` crate with upcoming changes, since they're supposed to be backwards-compatible, but I'm not sure if this would be flexible enough.

---

> Ideally just require that JSON version >= header version.

Header is now always latest stable, because it makes no sense to maintain multiple versions of it.
So this condition will never be true for any older `extension_api.json`.

Or did you mean `<=`?

**Comment by Yarwin** [comment]
closed by https://github.com/godot-rust/gdext/pull/1583
